### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by LindsayL** [FabriceSalvaire/CodeReview#1]
Sorry, very new to all this.  I look the way your tool looks so I've spent quite awhile getting all the dependencies.

I have successfully (no errors) done "pip install CodeReview"
and manually built it with "python3.4 setup.py build" and "python3.4 setup.py install".

But how do I actually use your program? :S

I've tried ./start.sh but that just throws me a bunch of errors:
setenv.sh: line 5: /home/myuser/python-virtual-env/py3-pyqt5/bin/activate: No such file or directory
setenv.sh: line 7: append_to_ld_library_path_if_not: command not found
setenv.sh: line 8: append_to_python_path_if_not: command not found
./start.sh: line 11: ./tools/clean: No such file or directory
running build
running build_py
running build_ext
running build_scripts
./start.sh: line 17: ./tools/update-tags: No such file or directory
./start.sh: line 20: ./tools/check-license.sh: No such file or directory
./start.sh: line 23: ./tools/generate-rst: No such file or directory
./start.sh: line 25: cd: sphinx/: No such file or directory
./start.sh: line 26: ./make-html: No such file or directory

I've tried "python3.4 ApplicationBase.py" from python3.4/site-packages/CodeReview/Application
This does nothing.

One of those install attempts added a CodeReview directory under /usr/local/share/ but it's contents are limited to icons.

**Comment by FabriceSalvaire** [comment]
Executables are in the bin directory (pyqgit). Shell scripts are for dev only.

You can try to run the command `which pyqgit` to check the pip install.

Installation works at least in a virtual environment. But you can test it directly in the source directory, you just have to set PYTHONPATH to the source directory (and maybe LD_LIBRARY_PATH).

**Comment by LindsayL** [comment]
Thank you very much for the quick response!  Unfortunately I won't be able to try it until I am back at work.  I will update then!

**Comment by FabriceSalvaire** [comment]
Sorry I missed your message!

You have to add /usr/local/lib to LD_LIBRARY_PATH

`export  LD_LIBRARY_PATH= /usr/local/lib:$LD_LIBRARY_PATH`
