### ISSUE TITLE
Error while installing CodeReview in levenshtein_distance.c

### ISSUE THREAD

**Issue by damianw345** [FabriceSalvaire/CodeReview#40]
building 'CodeReview.TextDistance.levenshtein_distance_c' extension
creating build\temp.win32-3.6\Release\CodeReview\TextDistance
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\aa\include -IC:\Users\aa\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /TcCodeReview/TextDistance/levenshtein_distance.c /Fobuild\temp.win32-3.6\Release\CodeReview/TextDistance/levenshtein_distance.obj
levenshtein_distance.c
**CodeReview/TextDistance/levenshtein_distance.c(60): error C2057: expected constant expression
CodeReview/TextDistance/levenshtein_distance.c(60): error C2466: cannot allocate an array of constant size 0
CodeReview/TextDistance/levenshtein_distance.c(60): error C2087: 'distance_matrix': missing subscript
CodeReview/TextDistance/levenshtein_distance.c(60): error C2133: 'distance_matrix': unknown size
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2**

**Comment by FabriceSalvaire** [comment]
**This C file is unused, it should be commented in the install file.**

However it looks like a C dialect issue since the code is not plain old ANSI C but C99 ???
