### ISSUE TITLE
pip install paths is inconsistent with paths in program

### ISSUE THREAD

**Issue by ysalmon** [FabriceSalvaire/CodeReview#47]
CodeReview assumes its icons are under its main installation location (ie. the CodeReview folder under pip's dist-packages) but during pip install these files are put in ``/usr/local/share/CodeReview/icons``.

This causes a crash upon start because the icon files cannot be loaded.

**Comment by drmrboy** [comment]
@ysalmon, This is already noted in Issue #42.
